name 'starburst-cookbook'           
maintainer 'Stephen ONeill'                
maintainer_email 'stephen.oneill@starburstdata.com' 
license 'All Rights Reserved'         
description 'Installs/Configures Startburst Enterprise' 
version '0.1.0'                       
